project_name: mist

builds:
  - id: mist-client
    main: ./cmd/mist-client
    binary: "mist-client-linux-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - mips
      - mipsle
      - riscv64
    goarm:
      - "7"
    gomips:
      - softfloat
    ignore:
      - goarch: amd64
        goarm: "7"
      - goarch: arm64
        goarm: "7"
      - goarch: mips
        goarm: "7"
      - goarch: mipsle
        goarm: "7"
      - goarch: riscv64
        goarm: "7"
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X mist/util.Version={{ .Version }} -X mist/util.Commit={{ .Commit }} -X mist/util.Date={{ .Date }}

  - id: mist-server
    main: ./cmd/mist-server
    binary: "mist-server-linux-{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
      - mips
      - mipsle
      - riscv64
    goarm:
      - "7"
    gomips:
      - softfloat
    ignore:
      - goarch: amd64
        goarm: "7"
      - goarch: arm64
        goarm: "7"
      - goarch: mips
        goarm: "7"
      - goarch: mipsle
        goarm: "7"
      - goarch: riscv64
        goarm: "7"
    flags:
      - -trimpath
      - -buildvcs=false
    ldflags:
      - -s -w -X mist/util.Version={{ .Version }} -X mist/util.Commit={{ .Commit }} -X mist/util.Date={{ .Date }}

archives:
  - id: mist-client
    builds:
      - mist-client
    name_template: "{{ .Binary }}"
    format: binary
  - id: mist-server
    builds:
      - mist-server
    name_template: "{{ .Binary }}"
    format: binary
